nelmio_api_doc:
    documentation:
        info:
            title: Warehouse API
            description: API for managing warehouse operations
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/warehouse